name: Release on version bump

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Get current version
        id: get_version
        run: echo "::set-output name=current_version::$(node -p "require('./package.json').version")"

      - name: Check if version has changed
        id: version_changed
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "$(node -p "require('./package.json').version")" != "${{ steps.get_version.outputs.current_version }}" ]; then
            echo "::set-output name=version_changed::true"
          else
            echo "::set-output name=version_changed::false"
          fi

      - name: Publish packages
        if: steps.version_changed.outputs.version_changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        run: |
          npm version --no-git-tag-version patch
          npm run build
          npm publish
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          echo "@<GITHUB_USERNAME>:registry=https://npm.pkg.github.com" >> .npmrc
          npm publish --access public
