name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm ci

    - name: Build package
      run: npm run build

    - name: Publish package
      uses: actions/npm@v1
      with:
        args: publish

    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release v${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload package to GitHub registry
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: './'